'use strict'

import calculateSpaceAfterCrossStaveUnitByMinUnitDurationOnPageLineAndItsMinDurationAmongAccumulatorsForEachVoiceConsideringCasesWhenItIsGraceCrossStaveUnit from '#msq/drawer/elements/layout-and-styles/unit-spacing/calculateSpaceAfterCrossStaveUnitByMinUnitDurationOnPageLineAndItsMinDurationAmongAccumulatorsForEachVoiceConsideringCasesWhenItIsGraceCrossStaveUnit.js'

export default function (minDurationAmongAccumulatorsForEachVoiceInLastCrossStaveUnitConsideringCasesWhenItIsGraceCrossStaveUnit, minUnitDurationOnPageLine, compressUnitsByNTimes, stretchUnitsByNTimes, styles) {
  return Math.max(
    styles.minSpaceAtTheEndOfMeasure,
    calculateSpaceAfterCrossStaveUnitByMinUnitDurationOnPageLineAndItsMinDurationAmongAccumulatorsForEachVoiceConsideringCasesWhenItIsGraceCrossStaveUnit({ minDurationAmongAccumulatorsForEachVoiceConsideringCasesWhenItIsGraceCrossStaveUnit: minDurationAmongAccumulatorsForEachVoiceInLastCrossStaveUnitConsideringCasesWhenItIsGraceCrossStaveUnit, atTheEndOfMeasure: true }, minUnitDurationOnPageLine, compressUnitsByNTimes, stretchUnitsByNTimes, styles)
  )
}
